---
- hosts: deb
  become: true

  pre_tasks:
    - name: Config
      include_vars: vars.yml

    - name: apt cache update & Upgrade
      apt:
        update_cache: true
        cache_valid_time: 3600
      when:
        - ansible_facts.os_family == "Debian"

  tasks:
    - name: Setup Docker.
      import_tasks: tasks/docker.yml

    - name: Install Nginx Proxy Manager
      import_tasks: tasks/proxy.yml
    
    - name: install portainer
      import_tasks: tasks/portainer.yml
      when: portainer_enable