---
- hosts: all
  become: true

  pre_tasks:
    - name: Config
      ansible.builtin.include_vars: vars.yml

    - name: Apt cache update
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when:
        - ansible_facts.os_family == "Debian"

    - name: Apt Upgrade
      ansible.builtin.apt:
        upgrade: true
      when:
        - ansible_facts.os_family == "Debian"

    - name: Yum cache update & upgrade
      ansible.builtin.yum:
        name: "*"
        state: latest
        update_cache: true
      when:
        - ansible_facts.os_family == "RedHat"

  tasks:

    - name: Install packages/prerequisites
      ansible.builtin.import_tasks: tasks/packages.yml

    - name: Setup Docker.
      ansible.builtin.import_tasks: tasks/docker.yml

    - name: Install Nginx Proxy Manager with SQLite
      ansible.builtin.import_tasks: tasks/proxy.yml
      when: not proxy_with_mysql

    - name: Install Nginx Proxy Manager with MySQL
      ansible.builtin.import_tasks: tasks/proxy-mysql.yml
      when: proxy_with_mysql

    - name: Install portainer
      ansible.builtin.import_tasks: tasks/portainer.yml
      when: portainer_enable
