---
- hosts: all
  become: true

  pre_tasks:
    - name: Config
      include_vars: vars.yml

    - name: apt cache update & Upgrade
      apt:
        update_cache: true
        cache_valid_time: 3600
        upgrade: full
      when:
        - ansible_facts.os_family == "Debian"

    - name: update yum cache for redhatfamily
      yum:
        update_cache: true
      when:
        - ansible_facts.os_family == "RedHat"

    - name: upgrade all redhat
      yum: 
        name: "*"
        state: latest
      when:
        - ansible_facts.os_family == "RedHat"

  tasks:

    - name: Install packages/prerequisites
      import_tasks: tasks/packages.yml
      
    - name: Setup Docker.
      import_tasks: tasks/docker.yml

    - name: Install Nginx Proxy Manager
      import_tasks: tasks/proxy.yml
    
    - name: install portainer
      import_tasks: tasks/portainer.yml
      when: portainer_enable