---

- name: If Docker is already installed?.
  ansible.builtin.command: which docker
  failed_when: false
  changed_when: false
  check_mode: false
  register: docker_present

- name: Download Docker install script.
  ansible.builtin.get_url:
    url: https://get.docker.com/
    dest: /tmp/get-docker.sh
    mode: 0775
  when:
    - docker_present.rc == 1
    - ansible_facts.os_family != "RedHat"

- name: Run Docker install script.
  ansible.builtin.command: /tmp/get-docker.sh
  failed_when: false
  changed_when: false
  check_mode: false
  environment:
    CHANNEL: stable
  when:
    - docker_present.rc == 1
    - ansible_facts.os_family != "RedHat"

- name: Add docker repo to yum
  ansible.builtin.command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  failed_when: false
  changed_when: false
  check_mode: false
  when:
    - docker_present.rc == 1
    - ansible_facts.os_family == "RedHat"

- name: Update yum cache
  ansible.builtin.yum:
    update_cache: true
  when:
    - ansible_facts.os_family == "RedHat"
    - docker_present.rc == 1

- name: Install docker on redhat
  ansible.builtin.yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
  when:
    - docker_present.rc == 1
    - ansible_facts.os_family == "RedHat"

- name: Start docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Create group docker
  ansible.builtin.group:
    name: docker
    state: present

- name: Adding existing user to group sudo
  ansible.builtin.user:
    name: '{{ ansible_user }}'
    groups: docker
    append: true

- name: Reset connection
  ansible.builtin.meta: reset_connection
