---

- name: Install Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when:
    - ansible_facts.os_family == "Debian"

- name: Add Docker PPA for Debian
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present
  when:
    - ansible_facts.os_family == "Debian"

- name: Add docker ppa for redhat family
  yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable Repo
    baseurl: https://download.docker.com/linux/centos/docker-ce.repo
  when:
        - ansible_facts.os_family == "RedHat"
  

- name: Install Docker-ce debian
  apt:
    name: docker-ce
    update_cache: yes
    state: latest
  when:
    - ansible_facts.os_family == "Debian"

- name: Install docker on redhat
  yum:
    name: 
    - docker-ce
    - docker-ce-cli
    - containerd.io
  when:
        - ansible_facts.os_family == "RedHat"

- name: Start docker
  service:
    name: docker
    state: started
    enabled: true

- name: Create group docker
  group:
    name: docker
    state: present

- name: adding existing user '{{ user }}' to group sudo
  user:
    name: '{{ansible_user}}'
    groups: docker
    append: yes
- name: Reset connection
  meta: reset_connection