---
- name: Create group
  group:
    name: "{{group}}"
    state: present

- name: adding existing user '{{ user }}' to group sudo
  user:
    name: '{{user}}'
    groups: "{{group}}"
    append: yes
