---

- name: Install Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker PPA
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Install Docker-ce
  apt:
    name: docker-ce
    update_cache: yes
    state: latest

- name: Start docker
  service:
    name: docker
    state: started
    enabled: true

- name: Create group docker
  group:
    name: docker
    state: present

- name: adding existing user '{{ user }}' to group sudo
  user:
    name: '{{ansible_user}}'
    groups: docker
    append: yes
- name: Reset connection
  meta: reset_connection