---
- name: Create group '{{group}}'
  group:
    name: "{{group}}"
    state: present

- name: adding existing user '{{ user }}' to group sudo
  user:
    name: '{{ansible_user}}'
    groups: "{{group}}"
    append: yes
