---

- name: Install packages/prerequisites "Debian"
  apt:
    name:
    - curl
    - python3-pip
    - apt-transport-https
    - ca-certificates
    - software-properties-common
    - virtualenv
    - python3-setuptools
    state: latest
    cache_valid_time: 3600
  when: 
    - ansible_facts.os_family == "Debian"

- name: Install packages on redhatfamily
  yum: 
    - curl
    - python3
    - python3-pip
    - lvm2
    - device-mapper-persistent-data
    - yum-utils

- name: install python docker SDK
  pip:
    name: docker