---

- name: Install packages/prerequisites
  apt:
    name:
    - curl
    - python3-pip
    - apt-transport-https
    - ca-certificates
    - software-properties-common
    - virtualenv
    - python3-setuptools
    state: latest
    cache_valid_time: 3600
  
- name: install python docker SDK
  pip:
    name: docker